# capsule-helm/Application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://repo.helmforge.dev'
    chart: cloudflared
    targetRevision: 1.5.14 
    helm:
      values: |
        tunnel:
          quickTunnel:
            enabled: false
          existingSecret: cloudflare-tunnel-secret
          existingSecretKey:  credentials.json
        replicaCount: 1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudflare-tunnel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true