[proxmox]
stella-01 ansible_host=192.168.0.100 ansible_user=root ansible_ssh_private_key_file=/root/.ssh/stella-01

[k8s_nodes]
master ansible_host=10.0.1.3 ansible_user=root ansible_ssh_private_key_file=/root/.ssh/id_ed25519
; worker-1 ansible_host=10.0.1.4 ansible_user=root ansible_ssh_private_key_file=/root/.ssh/id_ed25519

[k8s_nodes:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -i /root/.ssh/stella-01 -W %h:%p root@192.168.0.100" -o StrictHostKeyChecking=no'