apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce # 単一ノードからの読み書き
  storageClassName: seaweedfs-storage 
  resources:
    requests:
      storage: 10Gi # 確保したい容量