apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel # cloudflaredを動かすNamespace
spec:
  refreshInterval: "1h"       # Vaultからの自動同期インターバル
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-secret # 生成される K8s Secret の名前
    creationPolicy: Owner
  data:
    - secretKey: api-token   # 生成される K8s Secret 内のキー名
      remoteRef:
        key: cloudflare/tunnel # Vault上のパス（secret/data/ の後は省略可）
        property: api-token         # Vault上のJSONフィールド名