apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel # cloudflaredを動かすNamespace
spec:
  refreshInterval: "1h"       # Vaultからの自動同期インターバル
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-secret # 生成される 1つの K8s Secret の名前
    creationPolicy: Owner
  data:
    # 1つ目のキー: credentials.json
    - secretKey: credentials.json
      remoteRef:
        key: cloudflare/tunnel
        property: api-token

    # # 2つ目のキー: cert.pem
    # - secretKey: cert.pem
    #   remoteRef:
    #     key: cloudflare/tunnel
    #     property: cert.pem