# capsule-config/config.yaml
apiVersion: capsule.clastix.io/v1beta2
kind: CapsuleConfiguration
metadata:
  name: default
spec:
  cacheInvalidation: 0h30m0s
  enableTLSReconciler: false
  rbac:
    enabled: true
  # users:
  #   - kind: Group
  #     name: system:authenticated
  userGroups:
      - capsule.clastix.io
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: capsule-proxy
  namespace: capsule-system
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: default
  hostnames:
  - "kubernetes.pitpe.app" # 利用するホスト名またはドメイン名に変更してください
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: capsule-proxy
      port: 9001
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: capsule-proxy-tls-policy
  namespace: capsule-system
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: capsule-proxy
  validation:
    caCertificateRefs:
      - group: ""
        kind: ConfigMap #secret非対応だってさ
        #      kubectl -n capsule-system create configmap capsule-proxy-ca-configmap \
        #      --from-literal=ca.crt="$(kubectl -n capsule-system get secret capsule-proxy-root-secret -o jsonpath='{.data.ca\.crt}' | base64 -d)"
        #こうやってconfigmapを作っておく必要がある
        name: capsule-proxy-ca-configmap
    hostname: "capsule-proxy.capsule-system.svc"  # 証明書の SAN (Subject Alternative Name) に合わせる