apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - cloudflared.yaml
  - cloudnative-pg.yaml
  - external-secrets.yaml
  - immich.yaml
  - node-feature-discovery.yaml
  - vault.yaml
  - seaweedfs.yaml
  - seaweedfs-csi-driver.yaml