apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  #namespace: cert-manager
  namespace: cert-manager
type: Opaque
stringData:
  api-token: YZp44wH_-M8Z63w1mv1-aeS64q-2I-mSCpwYxiEG
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  acme:
    email: pitpencilcase@gmail.com # your emailadress
    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pitpe-app-certificate
  namespace: envoy-gateway-system
spec:
  secretName: pitpe-app-tls 
  dnsNames:
    - "*.pitpe.app"
    - "pitpe.app"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer