apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: envoy-gateway-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.0.200/32 # Envoy Gateway専用の固定IP
  autoAssign: true
  serviceAllocation:
    serviceSelectors:
      - matchLabels:
          app: envoy-gateway # 特定のラベルが付いたServiceのみこのプールを使用可能
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  #- 10.0.1.200-10.0.1.254
  - 192.168.0.201-192.168.0.254
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - default