# capsule-helm/Application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capsule-helm
  namespace: argocd
  annotations:
    #先にcert-managerをインストールするため、sync-waveを1に設定
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://projectcapsule.github.io/charts'
    chart: capsule
    targetRevision: 0.13.*
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: capsule-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true