#capsule-config/Application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capsule-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/e331-1/stella-k8s.git'
    targetRevision: HEAD
    path: manifests/capsule-config # config.yaml が置いてあるパス
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: capsule-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true