apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-oci-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: cert-manager-oci
  type: helm
  url: quay.io/jetstack/charts
  enableOci: "true"