# capsule-helm/Application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://cloudflare.github.io/helm-charts'
    chart: cloudflare-tunnel
    targetRevision: 0.3.2
    helm:
      values: |
        # 事前に作成したSecretを参照
        cloudflare:
          secretName: cloudflare-tunnel-secret
          ingress:
            - hostname: "pitpe.app"
              service: https://my-service.my-namespace.svc.cluster.local:443
              originRequest:
                noTLSVerify: true # 内部HTTPSの証明書検証を無効化
            - hostname: "*.pitpe.app"
              service: https://my-service.my-namespace.svc.cluster.local:443
              originRequest:
                noTLSVerify: true # 内部HTTPSの証明書検証を無効化
            - service: http_status:404
        replicaCount: 1
      
      volumeMounts:
        - name: cert-volume
          mountPath: /etc/cloudflared/cert.pem
          subPath: cert.pem
          readOnly: true

      volumes:
        - name: cert-volume
          secret:
            secretName: cloudflare-tunnel-cert-secret

      env:
        - name: TUNNEL_ORIGIN_CERT
          value: /etc/cloudflared/cert.pem
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudflare-tunnel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true