#capsule-config/Application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/e331-1/stella-k8s.git'
    targetRevision: HEAD
    path: manifests/dex-config # config.yaml が置いてあるパス
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true