# capsule-helm/Application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.dexidp.io'
    chart: dex
    targetRevision: 0.24.1 
    helm:
      values: |
        https:
          # -- Enable the HTTPS endpoint.
          enabled: false

        config:        
          connectors:
            - type: google
              id: google
              name: Google
              config:
                clientID: $GOOGLE_CLIENT_ID
                clientSecret: $GOOGLE_CLIENT_SECRET
                redirectURI: https://dex.pitpe.com/callback
                groups:
                  - capsule.clastix.io

          # Device Flow (CLI用) を有効化する場合
          strategy:
            device:
              userCode: choice

          staticClients:
            - id: kubernetes-device
              name: 'Kubernetes CLI (Device Flow)'
              secret: "${var.device_client_secret}"
              grantTypes:
                - authorization_code                       # ← 通常のブラウザ自動起動用
                - urn:ietf:params:oauth:grant-type:device_code  # ← Device Flow (暗証番号) 用
                - refresh_token                            # ← トークン自動更新用
              redirectURIs:
                - http://localhost:8000/callback           # kubeloginのローカルリダイレクト用
                - http://127.0.0.1:8000/callback

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true