# capsule-helm/Application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'docker.io/envoyproxy'
    chart: gateway-helm
    targetRevision: 1.8.*
    helm:
      valuesObject:
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.0.200
      # Argo CD 側で Helm リリース名を明示したい場合は releaseName を指定できます
      releaseName: eg
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
