apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/e331-1/stella-k8s.git'
    targetRevision: HEAD
    path: manifests/immich # config.yaml が置いてあるパス

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true