apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'ghcr.io/immich-app/immich-charts'
    chart: immich
    targetRevision: 0.13.1 # お使いのチャートバージョン
    helm:
      valuesObject: 
        controllers:
          main:
            containers:
              main:
                image:
                  tag: v3.0.0
                env:
                  # Add the env vars to connect to your database here. see the example below
                  #
                  DB_HOSTNAME:
                    valueFrom:
                      secretKeyRef:
                        name: immich-database-app
                        key: host
                  DB_USERNAME: 
                    valueFrom:
                      secretKeyRef:
                        name: immich-database-app
                        key: username
                  DB_DATABASE_NAME:
                    valueFrom:
                      secretKeyRef:
                        name: immich-database-app
                        key: dbname
                  DB_PASSWORD:
                    valueFrom:
                      secretKeyRef:
                        name: immich-database-app
                        key: password

        server:
          env:
            LIBVA_DRIVER_NAME: "iHD"
          resources:
            limits:
              gpu.intel.com/i915: "1"
            requests:
              gpu.intel.com/i915: "1"
        
        immich:
          persistence:
            # Main data store for all photos shared between different components.
            library:
              # Automatically creating the library volume is not supported by this chart
              # You have to specify an existing PVC to use
              existingClaim: "immich-data-pvc"
        machine-learning:
          enabled: true
          persistence:
            cache:
              enabled: true
              type: emptyDir
              # Optional: to avoid downloading the ML models on every start, replace `type: emptyDir` above with:
              #   type: persistentVolumeClaim
              #   size: 10Gi
              #   accessMode: ReadWriteMany
              #   # storageClass: your-class


  destination:
    server: 'https://kubernetes.default.svc'
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true