#capsule-config/Application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    #metallb-helmの後にデプロイするため、sync-waveを2に設定
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/e331-1/stella-k8s.git'
    targetRevision: HEAD
    path: manifests/metallb-config # config.yaml が置いてあるパス
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true