apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - argocd-httproute.yaml
  - cert-manager-config.yaml
  - cilium-config.yaml
  - cloudflared-config.yaml
  - immich-manifests.yaml
  - intel-gpu-plugin.yaml
  - seaweedfs-manifests.yaml